### ISSUE TITLE
[bug] Build error in React Native Expo: `import.meta` is not supported in Hermes

### ISSUE THREAD

**Issue by LinhNguyen1059** [WalletConnect/web3modal-react-native#364]
### Link to minimal reproducible example

https://github.com/LinhNguyen1059/Expo-Web3.git

### Steps to Reproduce

Following this document to set up the AppKit in the React Native Expo app:

https://docs.reown.com/appkit/react-native/core/installation#react-native-cli

### Summary

After building the project, I received the following error: `"import.meta" is not supported in Hermes. Enable the unstable_transformImportMeta polyfill in babel-preset-expo to use this syntax.`

I then checked the AppKit dependency package and saw that they are using `valtio@1.13.2`. However, some packages use `valtio@1.11.2`.

According to this document, https://docs.expo.dev/router/reference/api-routes/#esm-not-supported, the old version of `valtio` uses ESM, which is not supported in React Native Expo right now.

### List of related npm package versions

```
"@react-native-async-storage/async-storage": "2.1.2",
"@react-native-community/netinfo": "11.4.1",
"@reown/appkit-wagmi-react-native": "^1.2.5",
"@tanstack/react-query": "^5.76.1",
"@walletconnect/react-native-compat": "^2.21.3",
"expo": "~53.0.9",
"expo-application": "~6.1.4",
"react-native": "0.79.2",
"react-native-get-random-values": "~1.11.0",
"viem": "^2.31.3",
"wagmi": "^2.15.6",
```

### Node.js Version

v20.18.1

### Package Manager

yarn@1.22.22

**Comment by ignaciosantise** [comment]
hey @LinhNguyen1059 👋 there are several libraries that are not working because of this change, zustand is another one  with issues (which is used by Wagmi)

Can you check if this works for you? https://github.com/pmndrs/zustand/discussions/1967#discussioncomment-12801707

**Comment by ignaciosantise** [comment]
@LinhNguyen1059 what i meant is that this solution will solve your valtio issue -> https://github.com/pmndrs/zustand/discussions/1967#discussioncomment-12801707

you need to enable `unstable_transformImportMeta` in order to make it work

**Comment by AndonMitev** [comment]
Hey friends after enablaning `unstable_transformImportMeta` wagmi is now throwing

`ERROR  TypeError: Cannot read property 'withConfig' of undefined, js engine: hermes`

Having those packages:
"wagmi": "^2.15.6",
"@privy-io/wagmi": "^1.0.4",

and this setup

```
import {
  createConfig,
  WagmiProvider as WagmiProviderExpo,
} from '@privy-io/wagmi';
import { http } from 'wagmi';
import { base } from 'wagmi/chains';

const config = createConfig({
  chains: [base],
  transports: {
    [base.id]: http(),
  },
});

export const WagmiProvider = ({ children }: { children: React.ReactNode }) => {
  return <WagmiProviderExpo config={config}>{children}</WagmiProviderExpo>;
};
```

I've also tried with:

```
import { createConfig, http, WagmiProvider as WagmiProviderExpo } from 'wagmi';
import { base } from 'wagmi/chains';

const config = createConfig({
  chains: [base],
  transports: {
    [base.id]: http(),
  },
});

export const WagmiProvider = ({ children }: { children: React.ReactNode }) => {
  return <WagmiProviderExpo config={config}>{children}</WagmiProviderExpo>;
};
```

but then throws

` ERROR  TypeError: window.addEventListener is not a function (it is undefined), js engine: hermes`

is there any additional 3rd party needed to use wagmi in react native?

**Comment by LinhNguyen1059** [comment]
Hi @AndonMitev, please follow this to set up wagmi in RN: https://docs.reown.com/appkit/react-native/core/installation#react-native-cli

**Comment by ignaciosantise** [comment]
> [@LinhNguyen1059](https://github.com/LinhNguyen1059) what i meant is that this solution will solve your valtio issue -> [pmndrs/zustand#1967 (comment)](https://github.com/pmndrs/zustand/discussions/1967#discussioncomment-12801707)
> 
> you need to enable `unstable_transformImportMeta` in order to make it work

Closing this one as is solved by enabling `unstable_transformImportMeta`.

@AndonMitev i'll follow your issue in #366

**Comment by alecananian** [comment]
Unfortunately `unstable_transformImportMeta` has not resolved it for me - does anybody have an example project they can share where this is working? I'm trying to find out what it is about my setup that is different. The Reown example uses Expo 52.x

**Comment by ignaciosantise** [comment]
@alecananian @sandoche this sample is using expo53 and it works https://github.com/reown-com/react-native-examples/blob/main/dapps/appkit-expo-wagmi

check the [babel config](https://github.com/reown-com/react-native-examples/blob/main/dapps/appkit-expo-wagmi/babel.config.js)
